name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: cclauss/buildozer

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: esim_pro_apk
          path: ./bin/*.apk
