name: Build Kivy APK

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies and build APK
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip libgl1-mesa-dev
          pip install --upgrade pip
          pip install cython buildozer
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: esim_pro_apk
          path: ./bin/*.apk
