name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies and build APK
      run: |
        sudo apt update
        sudo apt install -y python3-pip libtinfo6 unzip openjdk-17-jdk
        pip install buildozer cython
        buildozer init || true
        yes | buildozer android debug
        mkdir -p output
        cp bin/*.apk output/

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: esim_pro_apk
        path: output/*.apk
