name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with official kivy/buildozer Docker image
        uses: addnab/docker-run-action@v3
        with:
          image: kivy/buildozer
          options: -v ${{ github.workspace }}:/app
          run: |
            cd /app
            buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: esim_pro_apk
          path: ./bin/*.apk
